import mongoose from "mongoose";

const scopeItemSchema = new mongoose.Schema(
  {
    discipline: {
      type: String,
      required: true,
      trim: true,
      default: "Mechanical & Force",
    },
    parameter: {
      type: String,
      required: true,
      trim: true,
    },
    range: {
      type: String,
      required: true,
      trim: true,
      default: "0 - 100",
    },
    cmc: {
      type: String,
      required: true,
      trim: true,
      default: "± 0.5%",
    },
    masterStandard: {
      type: String,
      required: true,
      trim: true,
      default: "Master Reference Standard",
    },
    standardMethod: {
      type: String,
      required: true,
      trim: true,
      default: "IS / ISO Standard Method",
    },
    traceability: {
      type: String,
      trim: true,
      default: "NPL, New Delhi",
    },
    facility: {
      type: String,
      enum: ["On-Site & Permanent Lab", "On-Site Only", "Permanent Lab Only"],
      default: "On-Site & Permanent Lab",
    },
    active: {
      type: Boolean,
      default: true,
    },
  },
  { _id: true, timestamps: true }
);

const nablLabScopeSchema = new mongoose.Schema(
  {
    labName: {
      type: String,
      default: "ARCL Instruments Pvt. Ltd.",
      trim: true,
    },
    labCode: {
      type: String,
      default: "ARCL-LAB-01",
      trim: true,
      unique: true,
    },
    accreditationStandard: {
      type: String,
      default: "ISO/IEC 17025:2017",
      trim: true,
    },
    certificateNo: {
      type: String,
      default: "CC-4313",
      trim: true,
    },
    validUntil: {
      type: Date,
      default: () => new Date("2026-07-28"),
    },
    status: {
      type: String,
      enum: ["Active", "Under Renewal", "Suspended"],
      default: "Active",
    },
    masterTraceability: {
      type: String,
      default: "National Physical Laboratory (NPL), New Delhi & ERTL",
      trim: true,
    },
    referralCode: {
      type: String,
      default: "ARCL-LAB-01",
      trim: true,
    },
    referralRate: {
      type: Number,
      default: 30,
    },
    annualSubscriptionRate: {
      type: Number,
      default: 11000,
    },
    scopeItems: [scopeItemSchema],
  },
  { timestamps: true }
);

export const defaultArclNablScope = [
  {
    discipline: "Mechanical & Force",
    parameter: "Compression Testing Machine (CTM)",
    range: "0 to 2000 kN / 3000 kN",
    cmc: "± 0.50%",
    masterStandard: "Class 0.5 Master Load Cell & Proving Ring",
    standardMethod: "IS 14858 / ISO 7500-1 / ASTM C39",
    traceability: "NPL, New Delhi",
    facility: "On-Site & Permanent Lab",
    active: true,
  },
  {
    discipline: "Mechanical & Force",
    parameter: "Universal Testing Machine (UTM)",
    range: "0 to 1000 kN",
    cmc: "± 0.50%",
    masterStandard: "Class 0.5 Master Load Cell",
    standardMethod: "IS 1828 / ISO 7500-1",
    traceability: "NPL, New Delhi",
    facility: "On-Site & Permanent Lab",
    active: true,
  },
  {
    discipline: "Mechanical & Force",
    parameter: "CBR Testing Machine & Marshall Apparatus",
    range: "0 to 50 kN / 100 kN",
    cmc: "± 0.50%",
    masterStandard: "Proving Ring Class 1 (NPL Traceable)",
    standardMethod: "IS 2720 (Part 16) / ASTM D6927",
    traceability: "NPL, New Delhi",
    facility: "On-Site & Permanent Lab",
    active: true,
  },
  {
    discipline: "Dimensional",
    parameter: "Vernier Caliper / Digital Caliper",
    range: "0 to 300 mm / 600 mm",
    cmc: "± 0.010 mm",
    masterStandard: "Grade 0 Slip Gauge Set & Caliper Checker",
    standardMethod: "IS 3651 / JIS B7507",
    traceability: "NPL, New Delhi",
    facility: "On-Site & Permanent Lab",
    active: true,
  },
  {
    discipline: "Dimensional",
    parameter: "Outside Micrometer & Depth Gauge",
    range: "0 to 150 mm",
    cmc: "± 0.002 mm",
    masterStandard: "Grade 0 Slip Gauges",
    standardMethod: "IS 2967 / ISO 3611",
    traceability: "NPL, New Delhi",
    facility: "On-Site & Permanent Lab",
    active: true,
  },
  {
    discipline: "Dimensional",
    parameter: "Dial Gauge (Plunger & Lever Type)",
    range: "0 to 25 mm / 50 mm",
    cmc: "± 0.003 mm",
    masterStandard: "Dial Calibration Tester with Grade 0 Blocks",
    standardMethod: "IS 2092 / DIN 878",
    traceability: "NPL, New Delhi",
    facility: "On-Site & Permanent Lab",
    active: true,
  },
  {
    discipline: "Dimensional",
    parameter: "Standard Test Sieves (Brass / GI Mesh)",
    range: "20 µm to 125 mm",
    cmc: "± 4.5 µm",
    masterStandard: "Optical Profile Projector / Video Measuring System",
    standardMethod: "IS 460 (Part 1, 2, 3) / ISO 3310-1",
    traceability: "NPL, New Delhi",
    facility: "Permanent Lab Only",
    active: true,
  },
  {
    discipline: "Dimensional",
    parameter: "Cube, Beam & Cylindrical Moulds",
    range: "50mm, 70.6mm, 150mm, 100x100x500mm",
    cmc: "± 0.020 mm",
    masterStandard: "Precision Vernier & Digital Height Master",
    standardMethod: "IS 10086 / IS 516 / BS 1881",
    traceability: "NPL, New Delhi",
    facility: "On-Site & Permanent Lab",
    active: true,
  },
  {
    discipline: "Thermal & Environmental",
    parameter: "Hot Air Oven & Laboratory Drying Oven",
    range: "Ambient to 300 °C",
    cmc: "± 0.8 °C",
    masterStandard: "9-Point Pt-100 Standard RTD Data Acquisition System",
    standardMethod: "IS 962 / ASTM E145 / DKD-R 5-7",
    traceability: "ERTL (West) / NPL",
    facility: "On-Site & Permanent Lab",
    active: true,
  },
  {
    discipline: "Thermal & Environmental",
    parameter: "Humidity Chamber & Accelerated Curing Tank",
    range: "20 °C to 65 °C, 30% to 98% RH",
    cmc: "± 0.5 °C, ± 1.5% RH",
    masterStandard: "Master Multi-Channel Hygro-Thermometer Standard",
    standardMethod: "IS 962 / ASTM C511",
    traceability: "ERTL (West) / NPL",
    facility: "On-Site & Permanent Lab",
    active: true,
  },
  {
    discipline: "Thermal & Environmental",
    parameter: "Water Bath & Le-Chatelier Water Bath",
    range: "Ambient to 100 °C",
    cmc: "± 0.4 °C",
    masterStandard: "High-Precision Master RTD Probe",
    standardMethod: "IS 516 / IS 4031 / DKD-R 5-7",
    traceability: "NPL, New Delhi",
    facility: "On-Site & Permanent Lab",
    active: true,
  },
  {
    discipline: "Mass & Volume",
    parameter: "Precision Analytical Electronic Weigh Balance",
    range: "0 to 600 g (Resolution: 0.1 mg / 1 mg)",
    cmc: "± 0.2 mg",
    masterStandard: "E2 Class Standard Weight Set (OIML Compliant)",
    standardMethod: "IS 9281 (Part 1, 2) / OIML R76 / EURAMET cg-18",
    traceability: "RRSL / NPL, New Delhi",
    facility: "On-Site & Permanent Lab",
    active: true,
  },
  {
    discipline: "Mass & Volume",
    parameter: "High Capacity Platform Weighing Scale",
    range: "0 to 30 kg / 100 kg / 300 kg",
    cmc: "± 0.5 g",
    masterStandard: "F1 / M1 Class Cast Iron Standard Weights",
    standardMethod: "IS 9281 / OIML R76",
    traceability: "RRSL / NPL, New Delhi",
    facility: "On-Site & Permanent Lab",
    active: true,
  },
  {
    discipline: "Mass & Volume",
    parameter: "Volumetric Glassware (Cylinders, Pycnometers)",
    range: "10 ml to 2000 ml",
    cmc: "± 0.05 ml",
    masterStandard: "Gravimetric Method using E2 Standard Weights & Pure Water",
    standardMethod: "ISO 4787 / IS 878",
    traceability: "NPL, New Delhi",
    facility: "Permanent Lab Only",
    active: true,
  },
  {
    discipline: "Pressure & Vacuum",
    parameter: "Hydraulic Pressure Gauge & Transducers",
    range: "0 to 700 bar (0 to 10000 psi)",
    cmc: "± 0.25% FS",
    masterStandard: "Digital Dead Weight Tester / Master Digital Test Gauge",
    standardMethod: "IS 3624 / EN 837-1 / DKD-R 6-1",
    traceability: "NPL, New Delhi",
    facility: "On-Site & Permanent Lab",
    active: true,
  },
  {
    discipline: "Speed & Time",
    parameter: "Stop Watch & Digital Timer / RPM Indicator",
    range: "0 to 24 Hours / 0 to 10000 RPM",
    cmc: "± 0.10 sec / ± 1.0 RPM",
    masterStandard: "Master Non-Contact Optical Tachometer & GPS Clock Standard",
    standardMethod: "IS 13876 / NIST SP 960-12",
    traceability: "NPL, New Delhi",
    facility: "On-Site & Permanent Lab",
    active: true,
  },
];

const NablLabScope =
  mongoose.models.NablLabScope ||
  mongoose.model("NablLabScope", nablLabScopeSchema);

export default NablLabScope;
